/** Audit log action identifiers, shared so clients can label them. */
export const AUDIT_ACTIONS = {
  authLoginSucceeded: 'AUTH_LOGIN_SUCCEEDED',
  authLoginFailed: 'AUTH_LOGIN_FAILED',
  authLogout: 'AUTH_LOGOUT',
  vehicleCheckedIn: 'VEHICLE_CHECKED_IN',
  slotAssigned: 'SLOT_ASSIGNED',
  checkoutInitiated: 'CHECKOUT_INITIATED',
  paymentInitiated: 'PAYMENT_INITIATED',
  paymentSucceeded: 'PAYMENT_SUCCEEDED',
  paymentFailed: 'PAYMENT_FAILED',
  paymentCancelled: 'PAYMENT_CANCELLED',
  transactionFinalized: 'TRANSACTION_FINALIZED',
  receiptGenerated: 'RECEIPT_GENERATED',
  slotReleased: 'SLOT_RELEASED',
  slotBlocked: 'SLOT_BLOCKED',
  slotUnblocked: 'SLOT_UNBLOCKED',
  slotPriorityChanged: 'SLOT_PRIORITY_CHANGED',
  blockLocationUpdated: 'BLOCK_LOCATION_UPDATED',
  reportExported: 'REPORT_EXPORTED',
  userRegistered: 'USER_REGISTERED',
  identitySubmitted: 'IDENTITY_SUBMITTED',
  identityDocumentViewed: 'IDENTITY_DOCUMENT_VIEWED',
  userVerified: 'USER_VERIFIED',
  userVerificationRejected: 'USER_VERIFICATION_REJECTED',
  userActivated: 'USER_ACTIVATED',
  userDeactivated: 'USER_DEACTIVATED',
  userUpdated: 'USER_UPDATED',
  profileUpdated: 'PROFILE_UPDATED',
  vehicleRegistered: 'VEHICLE_REGISTERED',
  vehicleUpdated: 'VEHICLE_UPDATED',
  visitorAccessGranted: 'VISITOR_ACCESS_GRANTED',
  parkNowOffered: 'PARK_NOW_OFFERED',
  parkNowCancelled: 'PARK_NOW_CANCELLED',
  slotCreated: 'SLOT_CREATED',
  slotUpdated: 'SLOT_UPDATED',
  slotEnabled: 'SLOT_ENABLED',
  slotDisabled: 'SLOT_DISABLED',
  slotArchived: 'SLOT_ARCHIVED',
  slotRestored: 'SLOT_RESTORED',
  slotDeleted: 'SLOT_DELETED',
  blockCreated: 'BLOCK_CREATED',
  blockUpdated: 'BLOCK_UPDATED',
  zoneCreated: 'ZONE_CREATED',
  zoneUpdated: 'ZONE_UPDATED',
  noticeSent: 'NOTICE_SENT',
  securityStaffCreated: 'SECURITY_STAFF_CREATED',
  passwordReset: 'PASSWORD_RESET',
  exitRequested: 'EXIT_REQUESTED',
  exitRequestCancelled: 'EXIT_REQUEST_CANCELLED',
  checkoutQrScanned: 'CHECKOUT_QR_SCANNED',
  vehicleReleased: 'VEHICLE_RELEASED',
  identityDocumentDownloaded: 'IDENTITY_DOCUMENT_DOWNLOADED',
  shiftTemplateCreated: 'SHIFT_TEMPLATE_CREATED',
  shiftTemplateUpdated: 'SHIFT_TEMPLATE_UPDATED',
  shiftAssigned: 'SHIFT_ASSIGNED',
  shiftUpdated: 'SHIFT_UPDATED',
  shiftCancelled: 'SHIFT_CANCELLED',
  shiftCheckedIn: 'SHIFT_CHECKED_IN',
  shiftCheckedOut: 'SHIFT_CHECKED_OUT',
  shiftMissed: 'SHIFT_MISSED',
  cashHandoverRecorded: 'CASH_HANDOVER_RECORDED',
  cashDiscrepancyResolved: 'CASH_DISCREPANCY_RESOLVED',
  /** A request was refused by a consistency/security rule (metadata.code says which). */
  integrityRejected: 'INTEGRITY_REJECTED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
export const AUDIT_ACTION_CODES = Object.values(AUDIT_ACTIONS) as AuditAction[];

/** Entity types referenced by audit log entries. */
export const AUDIT_ENTITY_TYPES = {
  user: 'USER',
  parkingSession: 'PARKING_SESSION',
  parkingSlot: 'PARKING_SLOT',
  parkingBlock: 'PARKING_BLOCK',
  parkingZone: 'PARKING_ZONE',
  parkNowOffer: 'PARK_NOW_OFFER',
  payment: 'PAYMENT',
  receipt: 'RECEIPT',
  vehicle: 'VEHICLE',
  report: 'REPORT',
  identityDocument: 'IDENTITY_DOCUMENT',
  securityShift: 'SECURITY_SHIFT',
  shiftTemplate: 'SHIFT_TEMPLATE',
  cashHandover: 'CASH_HANDOVER',
} as const;

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];
export const AUDIT_ENTITY_TYPE_CODES = Object.values(AUDIT_ENTITY_TYPES) as AuditEntityType[];
